railsapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :frs
  get 'home/about_us'
  root'frs#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

railsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

railsapp/app/models/fr.rb
class Fr < ApplicationRecord
	belongs_to :user
end

railsapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :frs
end

railsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

railsapp/app/controllers/frs_controller.rb
class FrsController < ApplicationController
  before_action :set_fr, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /frs or /frs.json
  def index
    @frs = Fr.all
  end

  # GET /frs/1 or /frs/1.json
  def show
  end

  # GET /frs/new
  def new
    @fr = current_user.frs.build
  end

  # GET /frs/1/edit
  def edit
  end

  # POST /frs or /frs.json
  def create
    @fr = current_user.frs.build(fr_params)

    respond_to do |format|
      if @fr.save
        format.html { redirect_to fr_url(@fr), notice: "Fr was successfully created." }
        format.json { render :show, status: :created, location: @fr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frs/1 or /frs/1.json
  def update
    respond_to do |format|
      if @fr.update(fr_params)
        format.html { redirect_to fr_url(@fr), notice: "Fr was successfully updated." }
        format.json { render :show, status: :ok, location: @fr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frs/1 or /frs/1.json
  def destroy
    @fr.destroy

    respond_to do |format|
      format.html { redirect_to frs_url, notice: "Fr was successfully destroyed." }
      format.json { head :no_content }
    end
  end
def correct_user
    @fr= current_user.frs.find_by(id: params[:id])
    redirect_to frs_path, notice: "Not Authorized To Edit This Friend" if @fr.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fr
      @fr = Fr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fr_params
      params.require(:fr).permit(:first_name, :last_name, :email, :phone, :insta_id, :user_id)
    end
end

railsapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about_us
  end
end

railsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsapp/app/helpers/frs_helper.rb
module FrsHelper
end

railsapp/app/helpers/home_helper.rb
module HomeHelper
end

railsapp/app/views/frs/_form.html.erb
<div class="con">
        <div class="myC">
            <div class="ro">
                
                    <div class="myLC">
                  
                    <%= form_with(model: fr) do |form|%>
  <% if fr.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fr.errors.count, "error") %> prohibited this fr from being saved:</h2>

      <ul>
        <% fr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
<br/>
  <div>
    <%form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name,class:"myInput form-group",placeholder: "first_name"%>
  </div>

  <div>
    <%form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name,class:"myInput form-group",placeholder: "last_name" %>
  </div>

  <div>
    <%form.label :email, style: "display: block" %>
    <%= form.text_field :email,class:"myInput form-group",placeholder: "email" %>
  </div>

  <div>
    <%form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,class:"myInput form-group",placeholder: "phone" %>
  </div>

  <div>
    <%form.label :insta_id, style: "display: block" %>
    <%= form.text_field :insta_id,class:"myInput form-group",placeholder: "insta_id"%>
  </div>
   <div>
     <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class: "butt" %>
  </div>
  <br/>
  
<% end %>
</div>
                </div>
               
            
        </div>
    </div>

                 
               

railsapp/app/views/frs/_fr.html.erb
<div id="<%= dom_id fr %>">
  <p>
    <strong>First name:</strong>
    <%= fr.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= fr.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= fr.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= fr.phone %>
  </p>

  <p>
    <strong>Insta:</strong>
    <%= fr.insta_id %>
  </p>

</div>

railsapp/app/views/frs/edit.html.erb
<h1 class="st my-4">Edit Friend</h1>

<%= render "form", fr: @fr %>

<br>

<div>
  <%= link_to "Show this fr", @fr,class: "con1 butt" %> |
  <%= link_to "Back to frs", frs_path,class: " con1 butt" %>
</div>

railsapp/app/views/frs/index.html.erb
<% if user_signed_in? %>

      
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-8 center">
                            <h2>Friends <b>List</b></h2>
                            <br>
                        </div>

                    </div>
                    <table class="table table-striped table-hover table-bordered my-6" id="myTable">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>email</th>
                                <th>Phone</th>
                                <th>Insta_id </th>
                                <th></th>
                                
                            </tr>
                        </thead>
                        <tbody>
                           
                        
                          <% @frs.each do |fr| %>
        <% if fr.user == current_user %>
        <tr>
          <td>
<%= link_to fr.first_name + ' ' + fr.last_name, fr ,style: "color:blue"%>


          </td>
          
          <td><%= fr.email %></td>
          <td><%= fr.phone %></td>
          <td><%= fr.insta_id %></td>
          
          
          
          
          
          <td><%= button_to 'Delete', fr, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
        <% end %>
      <% end %> 
                    
                        </tbody>
                    </table>
                    
            </div>
        </div>
     <br/>
<%= link_to 'New Friend', new_fr_path, class:"btn btn-secondary" %>
<% else %>
<div class="container c my-4">
<h1 class="h1 mx-5">Hello</h1>
<h2 class="h1">This is my first Rails Webpage...
<%= image_tag "1.jpg", style:"float:left;width:50%;height:100%" %></h2>
<h2 class="h">About</h2>
<%= image_tag "2.jpg", style:"float:right;width:350px;height:550px;padding:5px" %>
<% end %>

railsapp/app/views/frs/new.html.erb
<h1 class="st my-3">Add friend</h1>

<%= render 'form', fr: @fr%>
<div class=" ">
  <%= link_to "Back to friends", frs_path ,class: " con1 butt"%>
</div>

railsapp/app/views/frs/show.html.erb
<div class=" container my-4 jumbotron">
  <h1 class="display-4">
    <%= @fr.first_name %>
    <%= @fr.last_name %>
  </h1>
  <p class="lead">
    <%= @fr.email %>  | 
    <%= @fr.phone %>  |  
    <%= @fr.insta_id %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_fr_path(@fr), class:"btn btn-secondary" %>
  <br/>
 <br/>
<%= button_to 'Delete', @fr, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
   <br/>
<%= link_to 'Back',frs_path, class:"btn btn-dark" %>

</div>

railsapp/app/views/home/_header.html.erb
  
                                 <nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to "Friend App",root_path,class:"navbar-brand",style: "color:white" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      
      
     <% if user_signed_in? %>
       
          <%= link_to "Add Friend", new_fr_path, class:"nav-item nav-link",style: "color:white" %>
     


        
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-item nav-link",style: "color:white" %>
         
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-item nav-link",style: "background-color:red" %>
       
        
      <% else %>
    
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-item nav-link",style: "color:white" %>
  
          <%= link_to "Sign In", new_user_session_path, class:"nav-item nav-link",style: "color:white" %>
        
      <% end %>
        
        
    </ul>
   <!--  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

railsapp/app/views/home/about_us.html.erb
<h1>About Me</h1>

railsapp/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= image_tag "1.jpg", height: 300 %>

railsapp/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

railsapp/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <style>
        body {
            color: #566787;
            background: #f5f5f5;
            font-family: 'Roboto', sans-serif;
        }

        .table-responsive {
            margin: 30px 0;
        }

        .table-wrapper {
            min-width: 1000px;
            background: #fff;
            padding: 20px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        }

        .table-title {
            padding-bottom: 10px;
            margin: 0 0 10px;
            min-width: 100%;
        }

        .table-title h2 {
            margin: 8px 0 0;
            font-size: 22px;
        }

        .search-box {
            position: relative;
            float: right;
        }

        .search-box input {
            height: 34px;
            border-radius: 20px;
            padding-left: 35px;
            border-color: #ddd;
            box-shadow: none;
        }

        .search-box input:focus {
            border-color: #3FBAE4;
        }

        .search-box i {
            color: #a0a5b1;
            position: absolute;
            font-size: 19px;
            top: 8px;
            left: 10px;
        }

        table.table tr th,
        table.table tr td {
            border-color: #e9e9e9;
        }

        table.table-striped tbody tr:nth-of-type(odd) {
            background-color: #fcfcfc;
        }

        table.table-striped.table-hover tbody tr:hover {
            background: #f5f5f5;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child {
            width: 130px;
        }

        table.table td a {
            color: #a0a5b1;
            display: inline-block;
            margin: 0 5px;
        }

        table.table td a.view {
            color: #03A9F4;
        }

        table.table td a.edit {
            color: #FFC107;
        }

        table.table td a.delete {
            color: #E34724;
        }

        table.table td i {
            font-size: 19px;
        }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

        .pagination li a {
            border: none;
            font-size: 95%;
            width: 30px;
            height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 30px !important;
            text-align: center;
            padding: 0;
        }

        .pagination li a:hover {
            color: #666;
        }

        .pagination li.active a {
            background: #03A9F4;
        }

        .pagination li.active a:hover {
            background: #0397d6;
        }

        .pagination li.disabled i {
            color: #ccc;
        }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }

        .hint-text {
            float: left;
            margin-top: 6px;
            font-size: 95%;
        }

        .center {
            text-align: justify;
        }
    </style>
  </head>
  <body>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= render 'home/header' %>
    <%= yield %>
     

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
  <script>$(document).ready( function () {
    $('#myTable').DataTable();
    } );</script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>